### ISSUE TITLE
Can i use this plugin

### ISSUE THREAD

**Issue by NetherOwner** [NetherManiacsKingdom/Block-Hunt#1]

**Comment by erkam2002** [comment]
No

**Comment by erkam2002** [comment]
You can install it but i thing it crash i have not added cmds only start and disable message

**Comment by NetherOwner** [comment]
Kk and thank for joining our group

**Comment by NetherOwner** [comment]
You can work on EnderAuth too if you want because we soon done we only need 3 things

**Comment by DavidJBrockway** [comment]
what
